### ISSUE TITLE
Archive Command empty file name

### ISSUE THREAD

**Issue by yongqqqq** [AY2425S1-CS2103T-W10-4/tp#147]
The current archive command accepts the value pa/.json. By interpretation, this is an empty file name with the extension of .json. There is a need to consider if this value should be accepted.

**Comment by Jianwen0451** [comment]
<img width="908" alt="Screenshot 2024-11-04 at 11 13 15 PM" src="https://github.com/user-attachments/assets/a63e628a-4a11-4cc3-b136-77ea4f86bc98">
As you can see, it is a bit special in this case, with the name ".json" itself, it is a txt file that with name ".json" And it is a hidden file as well since it starts with a dot, ".". Loading can load from this file normally. I think this is just a special behavior based on the operating system. Lastly, the input pa/.json itself is an abnormal input. I think the best I can do in this place is to warn the user not to enter abnormal input to prevent undefined behavior due to lower level like OS

**Comment by Jianwen0451** [comment]
Since the file can be archived and loaded correctly, I won't determine this as a bug or feature flow (since it does what it should do). Even if it is, its severity is actually very low
